### PR TITLE
Font ligatures

### PR DESCRIPTION
**Pull request by svalaskevicius**
merged master into the branch, in some cases choosing the easiest solutions, but hopefully makes the work easier...

my first rust work :)

### CODE REVIEW

**Comment by svalaskevicius** [comment]
url matcher is probably the main thing to look at - had copied some removed structs to it so it compiles, but would likely need to be replaced to use textruns? also, it doesn't seem to be working, or maybe I don't know what to expect, but urls don't seem any different than normal text

**Comment by chrisduerr** [comment]
At a quick glance, I've been able to notice a few issues already where the master wasn't merged into this correctly. Some of which are indicated by Rust's warnings, others are more logical errors.

I feel like it might be easier to try to apply the PR on top of master, rather than trying to bring the PR back on the level of master.

**Comment by svalaskevicius** [comment]
Yeah, I agree, the amount of changed lines is much smaller that way, the commits might need to be squashed though as there are quite many of those in the PR too.

Do you know what's left for the PR in general? Cc @thunderseethe

**Comment by chrisduerr** [comment]
All the comments from my last review haven't been addressed as far as I remember.

**Comment by thunderseethe** [comment]
Thanks for picking up work on this!

I have some commits for the url stuff that swap it over to textruns but it had a bug where it didn't handle urls across lines appropriately. I'll push them to my PR so they can atleast be used as reference of how you'd swap it over to textruns

**Comment by svalaskevicius** [comment]
Thanks, I'll close this pr for now then :)

**Pull request closed without merging**
